export * as AuthService from "./auth";
export * as CertificationService from "./certification";
export * as ClinicService from "./clinic";
export * as CommentService from "./comment";
export * as ImageService from "./image";
export * as LikeService from "./like";
export * as MedicService from "./medic";
export * as QualificationService from "./qualification";
export * as ProductService from "./product";
