export const Categories = [
  "Audiology",
  "Bariatric",
  "Colon&Rectal",
  "Cardiovascular",
  "Dermatology",
  "Endocrine",
  "Gastroenterology&Hepatology",
  "Hematology",
  "Oncology",
  "Ophthalmology",
  "Oral&Maxillofacial",
  "Orthopedic",
  "Plastic",
  "Radiology",
  "Rheumatology",
  "Urology",
  "Fertility",
  "Neurology",
  "Obstetrics&Gynecology",
];

export const procedures = [
  {
    audiology: [
      "Auditory brainstem implant",
      "Auditory evoked potential test",
      "Aural rehabilitation",
      "Bone-anchored (osseointegrated) hearing aid surgery",
      "Cochlear implants",
      "Computerized dynamic posturography",
      "Custom ear protector fitting",
      "Electroacoustic assessments of hearing aids",
      "Electronystagmography",
      "Hearing aid fitting",
      "Hearing conservation services",
      "Hearing implant surgery",
      "Hearing monitoring services",
      "Newborn hearing screening",
      "Rotary-chair testing",
      "Swim mold fitting",
      "Tinnitus assessment",
      "Tinnitus management",
      "Vestibular testing",
    ],
  },
  {
    bariatric: [
      "Bariatric surgery",
      "Biliopancreatic diversion with duodenal switch (BPD/DS)",
      "Endoscopic sleeve gastroplasty",
      "Gastric banding removal",
      "Gastric bypass (Roux-en-Y)",
      "Intragastric balloon",
      "Laparoscopic adjustable gastric banding",
      "Minimally invasive surgery",
      "Revisional bariatric surgery",
      "Robotic surgery",
      "Sleeve gastrectomy",
      "Transoral outlet reduction",
    ],
  },
  {
    colonAndRectal: [
      "Anorectal surgery",
      "Colectomy",
      "Coloanal anastomosis",
      "Colonoscopy",
      "Colostomy",
      "Fecal microbiota (stool) transplant",
      "Flexible sigmoidoscopy",
      "Ileal conduit management",
      "Ileoanal anastomosis (J-pouch) surgery",
      "Ileostomy",
      "Intraoperative radiation therapy (IORT)",
      "Laparoscopic surgery",
      "Minimally invasive surgery",
      "Natural orifice transluminal endoscopic surgery",
      "Proctectomy",
      "Rectal prolapse surgery",
      "Robotic surgery",
      "Sacral nerve stimulation for fecal incontinence",
      "Single-incision laparoscopic surgery",
      "Transanal endoscopic microsurgery",
      "Transanal total mesorectal excision (TaTME)",
      "Urostomy",
      "Virtual colonoscopy",
    ],
  },
  {
    cardiovascular: [
      "Aortic root surgery",
      "Aortic valve repair and aortic valve replacement",
      "Atrial fibrillation ablation",
      "Atrial flutter ablation",
      "Cardiac ablation",
      "Cardiac catheterization",
      "Cardiac rehabilitation",
      "Cardiac resynchronization therapy",
      "Cardiovascular disease prevention",
      "Carotid angioplasty and stenting",
      "Carotid endarterectomy",
      "Congenital heart disease surgery",
      "Coronary artery bypass surgery",
      "Extracorporeal membrane oxygenation (ECMO)",
      "Heart transplant",
      "Heart valve surgery",
      "Implantable cardioverter-defibrillators (ICDs)",
      "Lung transplant",
      "Lung volume reduction surgery",
      "Minimally invasive heart surgery",
      "Minimally invasive surgery",
      "Mitral valve repair and mitral valve replacement",
      "Neonatal and pediatric heart surgery",
      "Nonpharmacological arrhythmia therapy",
      "Pacemaker",
      "Percutaneous valve procedures",
      "Pulmonary thromboendarterectomy",
      "Pulmonary valve repair and replacement",
      "Robotic surgery",
      "Ross procedure",
      "Transcatheter aortic valve replacement (TAVR)",
      "Tricuspid valve repair and tricuspid valve replacement",
      "Ventricular assist device (VAD)",
      "Video-assisted thoracoscopic surgery (VATS)",
    ],
  },
  {
    dermatology: [
      "Allergy education",
      "Allergy skin tests",
      "Botox injections",
      "Chemical peel",
      "Conscious sedation",
      "Cosmetic surgery",
      "Dermabrasion",
      "Dermal (soft tissue) fillers",
      "Dermatologic surgery",
      "Face-lift",
      "Facial fillers for wrinkles",
      "Feminizing hormone therapy",
      "Feminizing surgery",
      "Laser hair removal",
      "Laser resurfacing",
      "Laser surgery",
      "Light therapy for skin",
      "Masculinizing hormone therapy",
      "Masculinizing surgery",
      "Mohs surgery",
      "Mole removal",
      "Platelet-rich plasma injections",
      "Scar revision",
      "Sclerotherapy",
      "Skin cyst removal",
      "Tattoo removal",
      "UV light therapy",
    ],
  },
  {
    endocrine: [
      "Adrenalectomy",
      "Endoscopic thyroidectomy",
      "Insulinoma enucleation",
      "Laparoscopic surgery",
      "Lateral neck dissection",
      "Lymphadenectomy",
      "Minimally invasive parathyroidectomy (MIP)",
      "Minimally invasive surgery",
      "Neck dissection",
      "Pancreatectomy",
      "Pancreatic enucleation",
      "Parathyroidectomy",
      "Robotic adrenalectomy",
      "Robotic surgery",
      "Robotic ventral hernia repair",
      "Thyroidectomy",
    ],
  },
  {
    gastroenterologyAndHepatology: [
      "Anorectal function testing",
      "Bariatric surgery",
      "Barium enema",
      "Biliopancreatic diversion with duodenal switch (BPD/DS)",
      "Biofeedback",
      "Capsule endoscopy",
      "Cholecystectomy (gallbladder removal)",
      "Clinical nutrition counseling",
      "Clinical nutrition evaluation",
      "Colectomy",
      "Colonoscopy",
      "Constipation evaluation",
      "CT scan",
      "Diagnostic endoscopy",
      "Endoscopic mucosal resection",
      "Endoscopic sleeve gastroplasty",
      "Endoscopic ultrasound",
      "Esophagectomy",
      "Fecal incontinence evaluation",
      "Fecal occult blood test",
      "Flexible sigmoidoscopy",
      "Gastric bypass (Roux-en-Y)",
      "Hepatobiliary disease evaluation",
      "Hepatobiliary disease postoperative care",
      "HIDA scan",
      "Home enteral nutrition",
      "Ileoanal anastomosis (J-pouch) surgery",
      "Intestinal transit studies for GI motility disorders",
      "Intragastric balloon",
      "Liver biopsy",
      "Liver function tests",
      "Liver transplant",
      "Living-donor liver transplant",
      "Magnetic resonance elastography",
      "Minimally invasive anti-reflux procedures",
      "Minimally invasive anti-reflux surgery",
      "Minimally invasive surgery",
      "MRI",
      "Needle biopsy",
      "Photodynamic therapy",
      "Photodynamic therapy for advanced esophageal cancer",
      "Photodynamic therapy for Barrett's esophagus",
      "Provocative testing for noncardiac chest pain",
      "Radiofrequency treatment for GERD",
      "Radionuclide gastric studies for GI motility disorders",
      "Rectal prolapse surgery",
      "Robotic surgery",
      "Sleeve gastrectomy",
      "Splenectomy",
      "Stool DNA test",
      "Therapeutic endoscopy",
      "Ultrasound",
      "Upper endoscopy",
      "Video-assisted thoracoscopic surgery (VATS)",
      "Virtual colonoscopy",
    ],
  },
  {
    hematology: [
      "Ablation therapy",
      "Biological therapy for cancer",
      "Blood and bone marrow stem cell donation",
      "Blood transfusion",
      "Bone marrow transplant",
      "Cancer treatment",
      "Chemotherapy",
      "Experimental treatments",
      "Immunotherapy",
      "Targeted drug therapy",
      "Virotherapy",
    ],
  },
  {
    oncology: [
      "Biomarker Testing for Cancer Treatment",
      "Chemotherapy",
      "Hormone Therapy",
      "Hyperthermia",
      "Immunotherapy",
      "Photodynamic Therapy",
      "Radiation Therapy",
      "Stem Cell Transplant",
    ],
  },
  {
    ophthalmology: [
      "Anophthalmic socket surgery",
      "Balloon dacryoplasty",
      "Blepharoplasty",
      "Botox injections",
      "Brow lift",
      "Cataract surgery",
      "Contact lens fitting",
      "Cornea transplant",
      "Cosmetic surgery",
      "Custom orbital implants",
      "Descemet membrane endothelial keratoplasty (DMEK)",
      "Descemet stripping endothelial keratoplasty (DSEK)",
      "Ectropion repair",
      "Electrolysis for misdirected lashes",
      "Endoscopic dacryocystorhinostomy",
      "Entropion repair",
      "Eye exam",
      "Eyeglass fitting",
      "Eyelid retraction repair",
      "Facial fillers for wrinkles",
      "Fat grafting",
      "Gold weight eyelid implant",
      "Lacrimal surgery",
      "Laser cataract surgery",
      "LASIK eye surgery",
      "Ocular imaging",
      "Ocular surface reconstruction",
      "Oculoplastic surgery",
      "Orbital decompression",
      "Orbital fracture repair",
      "Orbital surgery",
      "Ptosis repair",
      "Refractive surgery",
      "Scar revision",
      "Scleral lens fitting",
      "Skin cancer reconstruction",
      "Visual electrophysiology",
    ],
  },
  {
    oralAndMaxillofacial: [
      "Alveolar bone grafting",
      "Arthrocentesis",
      "Arthroplasty",
      "Bone grafting for implants",
      "Buccal fat pad flap",
      "Cheek implants",
      "Chin surgery (genioplasty)",
      "Cosmetic dental surgery",
      "Cosmetic jaw surgery",
      "Costochondral rib grafts",
      "Dental implant surgery",
      "Distraction osteogenesis",
      "Double chin removal",
      "Facial contouring surgery",
      "Facial fracture repair",
      "Facial implant surgery",
      "Fibula free flap",
      "General anesthesia",
      "Iliac crest bone grafts",
      "Impacted tooth removal",
      "Intravenous sedation",
      "Jaw surgery",
      "Laser surgery",
      "Liposuction",
      "Mandibular osteotomy",
      "Mandibular reconstruction",
      "Maxillary osteotomy",
      "Maxillary reconstruction",
      "Maxillomandibular advancement surgery",
      "Microvascular reconstruction",
      "Nonvascularized bone graft",
      "Nose reconstruction",
      "Oral biopsy",
      "Oral cancer screening",
      "Orbital augmentation",
      "Orbital reconstruction",
      "Oroantral fistula repair",
      "Oronasal fistula repair",
      "Outer ear reconstruction",
      "Parotidectomy",
      "Partial TMJ replacement",
      "Radial forearm free flap",
      "Scar revision",
      "Sublingual gland removal",
      "Submandibular gland removal",
      "Temporalis flap",
      "TMJ disk surgery",
      "Tongue reduction surgery",
      "Tooth extraction",
      "Total TMJ replacement",
      "Tracheostomy",
      "Vascularized bone grafting",
      "Vermilionectomy",
      "Wisdom tooth extraction",
    ],
  },
  {
    orthopedic: [
      "ACL reconstruction",
      "Ankle arthroscopy",
      "Ankle reconstruction",
      "Ankle replacement",
      "Ankle surgery",
      "Autologous chondrocyte implantation (ACI)",
      "Bankart repair",
      "Bone grafting",
      "Bone metastasis surgery",
      "Bone reconstruction",
      "Brachial plexus surgery",
      "Bunion surgery",
      "Carpal tunnel surgery",
      "Cartilage repair",
      "Cartilage restoration",
      "Cervical spine fusion",
      "Congenital hand deformity correction",
      "Disk replacement",
      "Diskectomy",
      "Distal radioulnar joint replacement",
      "Elbow arthroscopy",
      "Elbow replacement surgery",
      "External fixation",
      "Femoral osteotomy",
      "Fibula free flap",
      "Finger fusion",
      "Finger joint replacement",
      "Finger reattachment",
      "Foot reconstruction",
      "Foraminotomy",
      "Free muscle transfer",
      "Fresh osteochondral allograft reconstruction",
      "Growing rods",
      "Guided growth in children",
      "Hand reconstruction",
      "Hand surgery",
      "Hand transplant",
      "Hemipelvectomy",
      "Hemivertebra resection",
      "Hip arthroscopy",
      "Hip core decompression",
      "Hip labral repair",
      "Hip preservation surgery",
      "Hip replacement",
      "Joint replacement",
      "Joint replacement revisions",
      "Knee fusion",
      "Knee osteotomy",
      "Knee reconstruction",
      "Knee replacement",
      "Laminectomy",
      "Ligament reconstruction of fingers",
      "Ligament reconstruction of forearm",
      "Ligament reconstruction of shoulder",
      "Ligament reconstruction of wrist",
      "Limb deformity correction",
      "Limb lengthening",
      "Limb salvage surgery",
      "Medial patellofemoral ligament reconstruction",
      "Mehta casting for infantile scoliosis",
      "Meniscus repair",
      "Meniscus transplantation",
      "Microvascular surgery",
      "Minimally invasive surgery",
      "Multiligament knee reconstruction",
      "Muscle transfers",
      "Nerve decompression",
      "Nerve grafts",
      "Nerve reconstruction",
      "Nerve transfer",
      "Nonunion surgery",
      "Offset procedures",
      "Osteotomy",
      "Partial knee replacement",
      "Pediatric cervical spine surgery",
      "Pelvic tumor surgery",
      "Periacetabular osteotomy (PAO)",
      "Physeal bar resection",
      "Posterior cruciate ligament (PCL) reconstruction",
      "Reverse shoulder replacement",
      "Revision of previous trauma surgery",
      "Robot-assisted partial knee resurfacing",
      "Rotationplasty",
      "Rotator cuff surgery",
      "Sacrectomy",
      "Sacroiliac joint fusions",
      "Shoulder arthroscopy",
      "Shoulder replacement surgery",
      "Soft tissue sarcoma surgery",
      "Spatial frame corrections",
      "Spinal deformity correction",
      "Spinal fusion",
      "Spine decompression",
      "Spine reconstruction",
      "Spine tumor surgery",
      "Tendon transfer",
      "Toe-to-thumb transfer",
      "Tommy John surgery",
      "Unicompartmental knee replacement",
      "Vascularized bone grafting",
      "Vascularized free fibula transfer",
      "Vertebral column resection",
      "Vertebroplasty",
      "Wrist arthroscopy",
      "Wrist fracture treatment",
      "Wrist fusion",
      "Wrist reconstruction",
      "Wrist replacement",
    ],
  },
  {
    plastic: [
      "Arm lift",
      "Blepharoplasty",
      "Body fat removal",
      "Body lift",
      "Botox injections",
      "Breast augmentation",
      "Breast cancer surgery",
      "Breast lift",
      "Breast reconstruction with flap surgery",
      "Breast reconstruction with implants",
      "Breast reduction surgery",
      "Brow lift",
      "Buttock lift",
      "Cheek lift",
      "Chemical peel",
      "Chemotherapy for breast cancer",
      "Chin surgery (genioplasty)",
      "Cleft lip repair",
      "Cleft palate repair",
      "CO-2 laser treatment",
      "Collagen injection",
      "Complex wound repair",
      "Cosmetic dental surgery",
      "Cosmetic jaw surgery",
      "Cosmetic surgery",
      "Craniofacial surgery",
      "Dermabrasion",
      "Double chin removal",
      "Ear reconstruction",
      "Electromyography (EMG)",
      "Endoscopic cosmetic surgery",
      "Endovenous laser therapy",
      "Face-lift",
      "Facial contouring surgery",
      "Facial feminization surgery",
      "Facial fillers for wrinkles",
      "Facial nerve rehabilitation",
      "Facial reanimation",
      "Facial reconstruction",
      "Facial rejuvenation",
      "Facial scar revision",
      "Fat grafting",
      "Feminizing hormone therapy",
      "Feminizing surgery",
      "Gender affirming surgery",
      "Gynecomastia surgery",
      "Hand surgery",
      "Jaw surgery",
      "Laser hair removal",
      "Laser resurfacing",
      "Lip surgery",
      "Liposuction",
      "Masculinizing hormone therapy",
      "Masculinizing surgery",
      "Microtia repair",
      "Microvascular surgery",
      "Minimally invasive surgery",
      "Mohs surgery",
      "Nasal valve repair",
      "Neck lift",
      "Non-surgical fat removal (VelaShape/UltraShape)",
      "Nose reconstruction",
      "Orbital reconstruction",
      "Otoplasty",
      "Parathyroidectomy",
      "Radiation therapy for breast cancer",
      "Rhinoplasty",
      "Robotic surgery",
      "Scar revision",
      "Sclerotherapy",
      "Septoplasty",
      "Skin cancer reconstruction",
      "Spider vein removal",
      "Tattoo removal",
      "Thigh lift",
      "Tooth alteration",
      "Tooth restoration",
      "Top surgery for transgender men and nonbinary people",
      "Top surgery for transgender women and nonbinary people",
      "Transgender voice therapy and surgery",
      "Tummy tuck",
      "Vascular blemish removal",
      "Wrinkle treatment",
    ],
  },
  {
    radiology: [
      "3D anatomical modeling",
      "3D mammogram",
      "7-tesla MRI",
      "Abdominal endovascular aneurysm repair (EVAR)",
      "Abdominal ultrasound",
      "Ablation therapy",
      "Adrenalectomy",
      "Angioplasty",
      "Arteriography",
      "Arthrogram",
      "Bile duct stone removal",
      "Biliary drainage",
      "Biliary stenting",
      "Bone density test",
      "Bone scan",
      "Bone tumor ablation",
      "Breast abscess drainage",
      "Breast biopsy",
      "Breast cyst aspiration",
      "Breast MRI",
      "Breast ultrasound",
      "Breast X-ray",
      "Cardiac CT scan",
      "Cardiac MRI",
      "Carotid angiogram",
      "Carotid angioplasty and stenting",
      "Carotid ultrasound",
      "Central venous catheterization",
      "Cerebral angiogram",
      "Chemical ablation with ethanol",
      "Chemoembolization",
      "Chemoembolization for liver cancer",
      "Chest drainage tube insertion",
      "Chest X-rays",
      "Cholangiogram",
      "Choline C-11 PET scan",
      "Cisternogram",
      "Computerized tomography (CT) urogram",
      "Contrast-enhanced mammography",
      "Cryoablation for cancer",
      "CT brain perfusion",
      "CT colonography",
      "CT coronary angiogram",
      "CT scan",
      "CT-guided aspirations",
      "CT-guided biopsy",
      "CT-guided drainage",
      "Defecating proctogram",
      "Dialysis access management",
      "Discogram",
      "Ductogram",
      "Embolization therapy",
      "Endorectal prostate MRI",
      "Endovenous laser therapy",
      "Fallopian tube catheterization",
      "Fetal MRI",
      "Fetal ultrasound",
      "Fine needle aspiration",
      "Fluoroscopy",
      "Fluoroscopy-guided biopsy",
      "Gallbladder tube placement",
      "Gastrostomy tube placement",
      "Heart scan (coronary calcium scan)",
      "Hemodialysis access maintenance",
      "HIDA scan",
      "Holmium laser prostate surgery",
      "Home enteral nutrition",
      "Hysterosonogram",
      "Ileal conduit management",
      "Inferior vena cava (IVC) filter retrieval",
      "Intraoperative magnetic resonance imaging (iMRI)",
      "Intrathecal chemotherapy",
      "Intravenous pyelogram",
      "Kidney biopsy",
      "Kidney tumor ablation",
      "Kyphoplasty",
      "Laser PVP surgery",
      "Liver tumor ablation",
      "Loopogram",
      "Lu 177 dotatate therapy",
      "Lung cancer screening",
      "Lung tumor ablation",
      "Magnetic resonance angiography",
      "Magnetic resonance elastography",
      "Mammogram",
      "Molecular breast imaging",
      "MRCP",
      "MRI",
      "MRI-guided biopsy",
      "MRI-guided breast biopsy",
      "MRI-guided focused ultrasound ablation",
      "MRI-guided focused ultrasound thalamotomy",
      "Myelogram",
      "Nephrostomy tube placement",
      "Paracentesis",
      "Pelvic ultrasound",
      "Percutaneous ablation",
      "Percutaneous transhepatic cholangiogram",
      "PET/CT scan",
      "PET/MRI scan",
      "Photodynamic therapy",
      "Portal hypertension management",
      "Positron emission mammography (PEM)",
      "Positron emission tomography scan",
      "Prostate artery embolization",
      "Prostate tumor ablation",
      "Radioactive seed localization",
      "Radioembolization for liver cancer",
      "Radiofrequency ablation for cancer",
      "Sclerotherapy",
      "Sentinel lymph node mapping",
      "Soft tissue tumor ablation",
      "SPECT scan",
      "Spinal angiography",
      "Spinal injections",
      "Spinal tumor ablation",
      "Stereotactic breast biopsy",
      "Stereotactic needle biopsy",
      "Thoracentesis",
      "Thrombolysis",
      "Thyroid ablation",
      "Thyroid fine needle aspiration",
      "Thyroid scan",
      "Tomosynthesis-guided breast biopsy",
      "Transjugular intrahepatic portosystemic shunt (TIPS)",
      "Transplant imaging evaluation",
      "Transvascular biopsy",
      "Ultrasound",
      "Ultrasound-guided biopsy",
      "Ureteral dilatation and stenting",
      "Urinary stone removal",
      "Uterine artery embolization",
      "Uterine fibroid ablation",
      "Venography",
      "Venous sampling",
      "Vertebroplasty",
      "Video-assisted thoracoscopic surgery (VATS)",
      "Videofluoroscopic swallowing study",
      "Virtual colonoscopy",
      "Whitaker test",
      "X-ray",
    ],
  },
  {
    rheumatology: [
      "Bone scan",
      "Cortisone shots",
      "Dual energy CT scan",
      "Hip replacement",
      "Joint scan",
      "Knee replacement",
      "MRI",
      "Nailfold videocapillaroscopy",
      "Synovial (joint) fluid analysis",
      "Ultrasound",
      "Ultrasound-guided cortisone injections",
      "Viscosupplementation",
      "X-ray",
    ],
  },
  {
    urology: [
      "Ablation therapy",
      "Adrenalectomy",
      "Artificial urinary sphincter",
      "Bladder augmentation",
      "Bladder removal surgery (cystectomy)",
      "Brachytherapy",
      "Chemotherapy",
      "Choline C-11 PET scan",
      "Circumcision (male)",
      "Cryoablation for cancer",
      "Donor nephrectomy",
      "Enterostomal therapy",
      "Facial feminization surgery",
      "Feminizing hormone therapy",
      "Feminizing surgery",
      "Genitourinary reconstruction",
      "Holmium laser prostate surgery",
      "Immunotherapy",
      "Kidney reconstruction",
      "Kidney-sparing surgery",
      "Laser PVP surgery",
      "Masculinizing hormone therapy",
      "Masculinizing surgery",
      "Minimally invasive surgery",
      "Neobladder reconstruction",
      "Nephrectomy (kidney removal)",
      "Neurogenic bladder and bowel management",
      "Penile implants",
      "Prostate biopsy",
      "Prostate brachytherapy",
      "Prostate laser surgery",
      "Prostate ultrasound",
      "Prostatectomy",
      "Radiofrequency ablation for cancer",
      "Retroperitoneal lymph node dissection for testicular cancer",
      "Robotic surgery",
      "Salvage therapy",
      "Top surgery for transgender men and nonbinary people",
      "Top surgery for transgender women and nonbinary people",
      "Transgender voice therapy and surgery",
      "Transurethral resection of the prostate (TURP)",
      "Ultrasound-guided prostate biopsy",
      "Ureteral stent exchange",
      "Ureteral stent placement",
      "Ureteroscopy",
      "Urethral bulking procedures",
      "Urinary diversion surgery",
      "Urinary sling procedures",
      "Urodynamic evaluation",
      "Varicocele correction (varicocelectomy)",
      "Vasectomy",
      "Vasectomy reversal",
    ],
  },
  {
    fertility: [
      "intrauterine insemination (IUI)",
      "in vitro fertilization (IVF)",
    ],
  },
  {
    neurology: [
      "Cerebrovascular (AVMs)",
      "Neuro-oncology (brain tumors)",
      "Spinal neurosurgery",
      "Functional and epilepsy neurosurgery",
      "General neurosurgery",
      "Trigeminal neuralgia and nerve compression syndromes",
      "Peripheral nerve injury",
      "Aneurysms",
      "Arteriovenous malformation (AVM)",
      "Brain tumors",
      "Carotid artery blockage/stenosis",
      "Cavitron (brain tumors)",
      "Cerebrovascular surgery",
      "Cortical mapping",
      "Epilepsy",
      "Functional neurosurgery",
      "Inoperable brain tumors high intensity laser probe",
      "Intraoperative angiography",
      "Minimally invasive surgery",
      "Parkinson’s Disease and tremors",
      "Peripheral nerve surgery",
      "Pituitary tumors",
      "Radiosurgery",
      "Skull base surgery",
      "Spine Surgery",
      "Stereotactic neurosurgery",
      "Surgical implantation of deep brain stimulators",
      "Surgical navigation",
      "Trigeminal Neuralgia",
    ],
  },
  {
    obstetricsAndGynecology: [
      "Abdominal hysterectomy",
      "Ablation therapy",
      "Amniotic band release surgery",
      "Anal sphincter repair",
      "Antepartum care",
      "Artificial anal sphincter implantation",
      "Assisted reproductive technology",
      "Biofeedback",
      "Birth control pills",
      "Bladder botox injection",
      "Bladder prolapse (cystocele) repair",
      "Chemotherapy",
      "Chorionic villus sampling",
      "CO-2 laser treatment",
      "Colposcopy",
      "Conization",
      "Contraceptive implant",
      "Cordocentesis",
      "C-section",
      "Cystourethroscopy",
      "Cytoreductive surgery",
      "Diagnostic hysteroscopy",
      "Diagnostic laparoscopy",
      "Egg donation",
      "Egg freezing",
      "Endometrial ablation",
      "Endometriosis surgery",
      "Enterocele repair",
      "Facial feminization surgery",
      "Female hormone replacement therapy",
      "Feminizing hormone therapy",
      "Feminizing surgery",
      "Fertility preservation",
      "Fertility sparing surgery",
      "Fetal cystoscopy",
      "Fetal endoscopic tracheal occlusion",
      "Fetal shunt placement",
      "Fetal surgery",
      "Fetal surgery for spina bifida",
      "Fetoscopic laser ablation",
      "Fetoscopy",
      "First trimester screening",
      "Genetic amniocentesis",
      "Genetic counseling",
      "Genetic testing",
      "Gestational surrogacy",
      "Hyperthermic intraperitoneal chemotherapy (HIPEC)",
      "Hysteroscopy",
      "In vitro fertilization (IVF)",
      "Intraoperative magnetic resonance imaging (iMRI)",
      "Intrauterine transfusion",
      "IUDs",
      "Laparoscopic radiofrequency ablation",
      "Laser therapy for vaginal atrophy",
      "Loop electrosurgical excision procedure",
      "Masculinizing hormone therapy",
      "Masculinizing surgery",
      "Midurethral sling",
      "Minimally invasive hysterectomy",
      "Minimally invasive surgery",
      "Minimally invasive surgical staging",
      "Myomectomy",
      "Oophorectomy (ovary removal surgery)",
      "Ovarian remnant removal",
      "Ovarian tissue cryopreservation",
      "Ovary transplant",
      "Pap smear",
      "Pelvic exam",
      "Pelvic exenteration",
      "Pelvic floor physical therapy",
      "Pelvic floor reconstruction",
      "Pelvic floor re-education",
      "Percutaneous tibial nerve stimulation",
      "Pessary fitting",
      "Pessary management",
      "Physical therapy",
      "Polypectomy",
      "Post-hysterectomy vaginal prolapse repair",
      "Preimplantation genetic diagnosis",
      "Preimplantation genetic screening",
      "Prenatal drug exposure counseling",
      "Prenatal screening",
      "Radiofrequency ablation",
      "Rectocele repair",
      "Rectovaginal fistula repair",
      "Robotic hysterectomy",
      "Robotic myomectomy",
      "Robotic surgery",
      "Sacral nerve stimulation",
      "Sentinel node biopsy",
      "Sperm donation",
      "Third-party reproduction",
      "Top surgery for transgender men and nonbinary people",
      "Top surgery for transgender women and nonbinary people",
      "Trachelectomy",
      "Transgender voice therapy and surgery",
      "Tubal ligation",
      "Tubal ligation reversal",
      "Urethral diverticulum surgery",
      "Urethral reconstruction",
      "Urinary bladder training",
      "Urodynamic evaluation",
      "Uterine artery embolization",
      "Uterine prolapse surgery",
      "Vaginal delivery",
      "Vaginal hysterectomy",
      "Vaginectomy",
      "Vesicovaginal fistula repair",
      "Vulvectomy",
    ],
  },
];
