export { default as Certification, type ICertification } from './Certification'
export { default as Clinic, type IClinic } from './Clinic'
export { default as Comment, type IComment } from './Comment'
export { default as Image, type IImage } from './Image'
export { default as Like, type ILike } from './Like'
export { default as Medic, type IMedic } from './Medic'
export { default as Qualification, type IQualification } from './Qualification'
export { default as User, type IUser } from './User';
export { default as Product, type IProduct } from './Product';